### ISSUE TITLE
Why plutus-pab and playground deps?

### ISSUE THREAD

**Issue by anton-k** [Plutonomicon/Shrinker#1]
I wonder why do we need plutus-pab and playground dependencies in the compiled code optimization library.
Can you please remove them if they are not used.

**Comment by Geometer1729** [comment]
My test-suite depends on pluto to compile my unit tests and pluto depends on them. I'm hoping to figure out a way to allow the library part to be used without meeting all the dependencies for the tests, failing that I'm going to look into either depending on a fork of pluto which removes them or a later version of pluto if it doesn't need them and a pr can fix it.

**Comment by Geometer1729** [comment]
I've removed them by moving to a fork of pluto.
